
{% set name = "MLWC" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ToAmano/{{ name }}/archive/refs/tags/v.{{ version }}.tar.gz
    sha256: fe912eb8240d32694c08ff8c957ae2ba1cf17eaa4bf9db56021ca515439c0aef
    
build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --prefix=$PREFIX

requirements:
  host:
    - python >=3.10
    - rdkit >=2023.03.0
    - setuptools 
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy >=1.19.5
    - pytorch
    - torchinfo
    - ase ==3.23.0
    - rdkit >=2023.03.0    
    - mdtraj
    - pyyaml
    - statsmodels
    - matplotlib-base

test:
  requires:
    - pip
  commands:
    - pip check
    - CPextract.py --help 
    - CPmake.py --help    
    - CPtrain.py --help   
    - python -c "import torch; print(torch.cuda.is_available())" 
about:
  home: https://github.com/ToAmano/MLWC
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: "A machine learning package for Wannier centers."

extra:
  recipe-maintainers:
    - ToAmano
